### ISSUE TITLE
能否发布一个新版本的release

### ISSUE THREAD

**Issue by zhongfly** [Apache553/SubtitleFontHelper#2]
由于目前已支持libass的自动加载字体，但只有论坛中提供附件下载，希望在github发布release方便下载

**Comment by Apache553** [comment]
现在整个软件正在被我重写。目前进度很快就能做出一个可用的版本来，所以我打算到那个时候再release

**Comment by zhongfly** [comment]
也许可以再发布一个新版本或者更新一下？比如添加一个图形界面来修改设置、建立索引 @Apache553
