### ISSUE TITLE
加载到字体列表

### ISSUE THREAD

**Issue by login404** [Apache553/SubtitleFontHelper#4]
现在是只有调用过的字体才在列表里显示
能否实现即使程序未调用过字体
仍然将索引里的所有字体加载到字体列表
我想用在游戏和其他软件上

**Comment by Apache553** [comment]
我认为这是不行的。如果将所有字体都载入，那么将会花费巨量的时间，并且从本质上来讲与把所有字体都安装到系统中没有太大的差别。

**Comment by login404** [comment]
> 我认为这是不行的。如果将所有字体都载入，那么将会花费巨量的时间，并且从本质上来讲与把所有字体都安装到系统中没有太大的差别。

可以做成选项默认不启用
全部安装到系统的话
部分软件(LibreOffice)字体显示会错乱
但其他软件都正常
使用该功能我可以只挂钩能正常显示软件
不正常显示的软件可以不挂钩
而且全部安装会占用系统盘空间
快捷方式安装的话文件又会被占用
卸载了还得重启系统才能操作
盘符变动还会失效
