### ISSUE TITLE
报错，我无法启动

### ISSUE THREAD

**Issue by milkbing** [Apache553/SubtitleFontHelper#7]
你好，我遇到了一些问题，无法加载，我应该怎么解决？
![Snipaste_2023-07-04_17-31-52](https://github.com/Apache553/SubtitleFontHelper/assets/49283001/870e3a2c-ab88-4a43-9ea9-e8f7f3b9ed4f)

**Comment by Apache553** [comment]
这个错误是配置文件有错误 无法读取 请检查配置文件的内容

**Comment by milkbing** [comment]
> 此错误是配置文件有错误 无法读取请检查配置文件的内容

我按照bilibili的一遍文章已经配置过了，下面是我的配置信息
![Snipaste_2023-07-05_14-04-30](https://github.com/Apache553/SubtitleFontHelper/assets/49283001/362a7836-1e47-4259-878b-7c0e3ae1a5e6)
![Snipaste_2023-07-05_14-05-16](https://github.com/Apache553/SubtitleFontHelper/assets/49283001/ccdd673d-9357-4072-a314-f7c59b2e3eb4)

<?xml version="1.0" encoding="UTF-8"?>
<ConfigFile wmiPollInterval="1000">
<IndexFile>‪E:\Download\[BeanSub&FZSD&LoliHouse] Kimetsu no Yaiba [WebRip 1080p HEVC-10bit AAC ASSx2]\[BeanSub&FZSD&LoliHouse] Kimetsu no Yaiba - Fonts\FontIndex.xml</IndexFile>
<MonitorProcess>mpc-hc64_nvo.exe</MonitorProcess>
<MonitorProcess>PotPlayerMini64.exe</MonitorProcess>
</ConfigFile>

**Comment by Apache553** [comment]
`&`在XML中是特殊字符 请将IndexFile中的`&`都替换成`&amp;`再试试

**Comment by milkbing** [comment]
没有成功，但是考虑到文件名称的原因，我把字体路径文件名的&全部改为了-，可以正常使用了，感谢你指出了问题的关键。
另外文件registerETW.ps1，这个用来注册的东西，是每次都需要安装和卸载吗？

**Comment by Apache553** [comment]
不需要 这个是用来在事件查看器里面输出一些日志的 安装与否不影响功能

**Comment by milkbing** [comment]
好的，感谢你的帮助
